name: Build and push docker images

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Push images to docker registry
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      PUSH: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Build and push docker images
        run: python3 build_and_push.py
